 # encoding: utf-8
 Universidad.find_or_create_by_nombre(nombre:'CFT Alexander von Humboldt') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Alpes') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Andrés Bello') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Austral') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Barros Arana') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Cámara de Comercio de Santiago') 
 Universidad.find_or_create_by_nombre(nombre:'CFT CEDUC - UCN') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Ceitec') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Cenco') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Centro Tecnológico Superior INFOMED') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Cepa de la III Región') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Ceponal') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Crecic') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Crownliet') 
 Universidad.find_or_create_by_nombre(nombre:'CFT de ENAC') 
 Universidad.find_or_create_by_nombre(nombre:'CFT de Enseñanza de Alta Costura Paulina Diard') 
 Universidad.find_or_create_by_nombre(nombre:'CFT de la Industria Gráfica INGRAF') 
 Universidad.find_or_create_by_nombre(nombre:'CFT de Tarapacá') 
 Universidad.find_or_create_by_nombre(nombre:'CFT del Medio Ambiente') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Diego Portales') 
 Universidad.find_or_create_by_nombre(nombre:'CFT DUOC UC') 
 Universidad.find_or_create_by_nombre(nombre:'CFT EDUCAP') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Escuela Culinaria Francesa ECOLE') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Escuela de Artes Aplicadas Oficios del Fuego') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Escuela de Intérpretes INCENI') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Escuela Superior de Administración de Negocios del Norte ESANE') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Esperanza Joven') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Estudio Profesor Valero') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Fontanar') 
 Universidad.find_or_create_by_nombre(nombre:'CFT ICEL') 
 Universidad.find_or_create_by_nombre(nombre:'CFT INACAP') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Instituto Central de Capacitación Educacional ICCE') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Instituto de Secretariado INSEC') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Instituto Superior Alemán de Comercio INSALCO') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Instituto Superior de Estudios Jurídicos CANON') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Instituto Tecnológico de Chile I.T.C.') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Iprosec') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Jorge Álvarez Echeverría') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Juan Bohon') 
 Universidad.find_or_create_by_nombre(nombre:'CFT La Araucana') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Laplace') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Los Leones') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Lota-Arauco') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Luis Alberto Vera') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Magnos') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Manpower') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Massachusetts') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Osorno') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Proandes (ex Soeduc Aconcagua)') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Prodata') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Profasoc') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Protec') 
 Universidad.find_or_create_by_nombre(nombre:'CFT San Agustín de Talca') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Santo Tomás') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Simón Bolcvar') 
 Universidad.find_or_create_by_nombre(nombre:'CFT Teodoro Wickel Kluwen') 
 Universidad.find_or_create_by_nombre(nombre:'CFT UCEVALPO') 
 Universidad.find_or_create_by_nombre(nombre:'CFT UDA') 
 Universidad.find_or_create_by_nombre(nombre:'CFT UValpo') 
 Universidad.find_or_create_by_nombre(nombre:'IP Adventista') 
 Universidad.find_or_create_by_nombre(nombre:'IP Agrario Adolfo Matthei') 
 Universidad.find_or_create_by_nombre(nombre:'IP AIEP') 
 Universidad.find_or_create_by_nombre(nombre:'IP Alemán Wilhelm von Humboldt') 
 Universidad.find_or_create_by_nombre(nombre:'IP Arturo Prat') 
 Universidad.find_or_create_by_nombre(nombre:'IP Campus') 
 Universidad.find_or_create_by_nombre(nombre:'IP Carlos Casanueva') 
 Universidad.find_or_create_by_nombre(nombre:'IP Chileno Británico de Cultura') 
 Universidad.find_or_create_by_nombre(nombre:'IP Chileno Norteamericano') 
 Universidad.find_or_create_by_nombre(nombre:'IP CIISA') 
 Universidad.find_or_create_by_nombre(nombre:'IP de Arte y Comunicación ARCOS') 
 Universidad.find_or_create_by_nombre(nombre:'IP de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'IP de Ciencias de la Computación Acuario Data') 
 Universidad.find_or_create_by_nombre(nombre:'IP de Ciencias y Artes INCACEA') 
 Universidad.find_or_create_by_nombre(nombre:'IP de Ciencias y Educación Helen Keller') 
 Universidad.find_or_create_by_nombre(nombre:'IP de ENAC') 
 Universidad.find_or_create_by_nombre(nombre:'IP de Los ángeles') 
 Universidad.find_or_create_by_nombre(nombre:'IP del Valle Central') 
 Universidad.find_or_create_by_nombre(nombre:'IP Diego Portales') 
 Universidad.find_or_create_by_nombre(nombre:'IP Dr. Virginio Gómez G.') 
 Universidad.find_or_create_by_nombre(nombre:'IP Duoc UC') 
 Universidad.find_or_create_by_nombre(nombre:'IP EATRI Instituto Profesional') 
 Universidad.find_or_create_by_nombre(nombre:'IP Escuela de Cine de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'IP Escuela de Contadores Auditores de Santiago') 
 Universidad.find_or_create_by_nombre(nombre:'IP Escuela Moderna de Música') 
 Universidad.find_or_create_by_nombre(nombre:'IP ESUCOMEX') 
 Universidad.find_or_create_by_nombre(nombre:'IP Hogar Catequístico') 
 Universidad.find_or_create_by_nombre(nombre:'IP IACC') 
 Universidad.find_or_create_by_nombre(nombre:'IP INACAP') 
 Universidad.find_or_create_by_nombre(nombre:'IP Instituto de Estudios Bancarios Guillermo Subercaseaux') 
 Universidad.find_or_create_by_nombre(nombre:'IP Instituto Internacional de Artes Culinarias y Servicios') 
 Universidad.find_or_create_by_nombre(nombre:'IP Instituto Nacional del Fútbol') 
 Universidad.find_or_create_by_nombre(nombre:'IP IPEGE') 
 Universidad.find_or_create_by_nombre(nombre:'IP La Araucana') 
 Universidad.find_or_create_by_nombre(nombre:'IP Latinoamericano de Comercio Exterior') 
 Universidad.find_or_create_by_nombre(nombre:'IP Libertador de Los Andes') 
 Universidad.find_or_create_by_nombre(nombre:'IP Los Lagos') 
 Universidad.find_or_create_by_nombre(nombre:'IP Los Leones') 
 Universidad.find_or_create_by_nombre(nombre:'IP Projazz') 
 Universidad.find_or_create_by_nombre(nombre:'IP Providencia') 
 Universidad.find_or_create_by_nombre(nombre:'IP Santo Tomás') 
 Universidad.find_or_create_by_nombre(nombre:'IP Vertical') 
 Universidad.find_or_create_by_nombre(nombre:'Pontificia Universidad Católica de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'Pontificia Universidad Católica de Valparaíso') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Academia de Humanismo Cristiano') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Adolfo Ibáñez') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Adventista de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Alberto Hurtado') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Arturo Prat') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Austral de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Autónoma de Chile') 
 Universidad.find_or_create_by_nombre(nombre:"Universidad Bernardo O'Higgins") 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Bolivariana') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Católica de la Santísima Concepción') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Católica de Temuco') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Católica del Maule') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Católica del Norte')  
 Universidad.find_or_create_by_nombre(nombre:'Universidad Católica Silva Henríquez') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Central de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Chileno Británica de Cultura') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Aconcagua') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Antofagasta') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Arte y Ciencias Sociales ARCIS') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Artes, Ciencias y Comunicación UNIACC') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Atacama') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Concepción') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de La Frontera') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de La Serena') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Las Américas') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Los Andes') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Los Lagos') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Magallanes') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Playa Ancha de Ciencias de la Educación') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Santiago de Chile') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Talca') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Tarapacá') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Valparaíso') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad de Viña del Mar') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad del Bío-Bío') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad del Desarrollo') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad del Mar') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad del Pacífico') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Diego Portales')  
 Universidad.find_or_create_by_nombre(nombre:'Universidad Finis Terrae') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Gabriela Mistral') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Iberoamericana de Ciencias y Tecnología UNICIT') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Internacional SEK') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad La Araucana') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad La República') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Los Leones (ex Universidad Marítima)') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Mayor') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Metropolitana de Ciencias de la Educación') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Miguel de Cervantes') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Nacional Andrés Bello') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Pedro de Valdivia') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad San Sebastián') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Santo Tomás') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Técnica Federico Santa María') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Tecnológica de Chile INACAP') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad Tecnológica Metropolitana') 
 Universidad.find_or_create_by_nombre(nombre:'Universidad UCINF') 